/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Morse;

import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testEncode() throws IOException {
        //given
        Encode encode = new Encode("sos");
        //when
        //then
        assertEquals("...---...",encode.EncodeWord() );

    }
}
