/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Morse;

import
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testEncode() {
        //given
        Encode encode = new Encode("sos");
        //when
        //then
        assertEquals("...---...",encode.EncodeWord() );

    }
}
